# Generated by Django 2.2.7 on 2020-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201018_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
