# Generated by Django 3.1 on 2020-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201022_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(db_index=True, max_length=30)),
                ('whom', models.CharField(db_index=True, max_length=30)),
                ('timestamp', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
